### ISSUE TITLE
Weekly Update 1

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#13]
__One sentence overview of your submission__
 This is the issue for my weekly update document

__I would like feedback on ...__ 
Anything that comes to mind

**Comment by alfarozavalae** [comment]
Please specify what this issue is for by adding the #[issuenumber] in the description (i.e. "#17 adding new stop words") that way we can comment it here. You're no longer required to do an issue for the weekly updates.
If you do not have any issue related to the weekly update, feel free to close this issue.

**Comment by alfarozavalae** [comment]
please close this issue. There is no commits or pull requests linked here so I am assuming you do not need this issue.
