### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#4]
This is the Project decomposition document.

Wasn't sure how in-depth I should go in regards to the website section

**Comment by jazzij** [comment]
An open source project a few students at Berea have been working on that might give you a place to start on the term frequency algorithm: https://github.com/jazzij/decode-diversity-statements/tree/master/stemnleafplot (uses jupyter notebook to run and display code result, it might also be a good tool for you to quickly iterate and test your python code: https://jupyter.org/)

**Comment by schweinsbergs** [comment]
I like that you've lessened the scope down to essentially just 4chan threads. What I learned from my webscraper is that they need to have specific functionality for each sight, which seems incredibly obvious, but I totally overlooked it at the time. It saves you from getting in over your head, especially if you're writing the web scraper yourself. 

I think overall this document could use a little more meat to it, I tend to over explain rather than under explain, just a little more information on what you mean. If it makes sense to you when you look back at it though, it makes sense to you and that's good.

**Comment by Alex-Craig** [comment]
You know a lot more about web scrapers than I so this actually had useful resources to use in my own project. When the words are sorted are they going to be put into similar groups based on their own likeness or have their own respective group. Like f**k vs f***ker, vs motherf***ker etc? Because these are all based around the F-word but can be used in different contexts.

**Comment by Bryar-Frank** [comment]
While this documentation shows a good breakdown of what the overall project is, I do not think it meets the requirements of the assignment fully. It is laid out into easy to understand parts; however, a greater focus on the functional components in this project will give a better sense of how this project will perform. Currently, it is a bit broad. For example, the three major components here are imports, exports, and website. While all of these are useful, the functional components should focus on how the data is being received, what components are using that data, analyzing the data, and sending new data to other components. Also, this document should be broken down into the sections that were mentioned in the guideline. For example, the presentation of your flowcharts in class showed a good understanding of your different components, how they interact with each other, and importance of what parts need to get done first. Breaking down this document into those sections would be so much more powerful a tool to help you focus on what your next goals will be. Again, this is a really good start, but please keep in mind these recommendation while working on your midterm documentation.
