### ISSUE TITLE
Deliverable #3

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#6]
__One sentence overview of your submission__
 Draft document for D3 Prototyping phase

__I would like feedback on ...__ 
Should I turn these diagrams into digital versions? I think I should it would be much prettier.

**Comment by jazzij** [comment]
Yes, definitely turn these diagrams into digital versions. There are online graph editors (google "UML chart maker") but you can also use a freehand program like excalidraw.com to make them

**Comment by jazzij** [comment]
Re system diagram: You might want to consider how each of the scripts might run separately. For example, if the visualizations on the website are interactive (i.e. generated dynamically when someone visits the page) or if they are just static images that are generated every 2 weeks when the scraper is run and displayed.

**Comment by jazzij** [comment]
I think Sam is looking into using MongoDB for storing large amounts of json formatted data. that might be something to try for longer term storage and for storing the original text for context vs processed text for analysis

**Comment by jazzij** [comment]
one thing to try in the NLTK toolkit is to identify n-grams in your text to find the phrases https://blog.xrds.acm.org/2017/10/introduction-n-grams-need/

**Comment by schweinsbergs** [comment]
Like Dr. Jones said, I think this is looking pretty solid. I don't really have much to add in the terms of criticism because it's hard to know what to add when your program is so concentrated to your idea, and I don't have a lot of good information to give you. I think your ideas are solid, I think you've got a decent grasp on what needs done, your flows look good and detailed. I also think it would be good to digitize it, which will make it easier to access and understand it later on.

**Comment by Alex-Craig** [comment]
I think this looks great! I do agree and say that you should turn the diagrams into digital versions to look more pretty.  I used draw.io for mine because it has a graph that can lock the shapes in place making the diagram look centered all throughout. I think your project could really come in handy. You definitely know what you are doing and on the right track to complete your project!

**Comment by Bryar-Frank** [comment]
Wonderful Data Flow Diagram! I love the digital versions and all of the commenting after the diagram to explain the different working parts. This is a good way to portray how your project will work in a finished state. For the Website Idea, a more interactive or modal design for your lo-fi prototype is necessary. Having a good User Task Flow Diagram or User End UI sketch would be a great way to show what happens "up front" when you can't see all of the background working.  |  Apart from that, I do think this submission is currently unsatisfactory, though it is really close to being good. You should only show the final product of your Lo-Fi prototype visualizations, and not the previous versions in your final submission. Also, please provide more in depth detail in your reflections that what is presented. For example, when you say, "made me realize some different things that I will need to think about," what things? how did this process bring up those questions?

**Comment by Bryar-Frank** [comment]
Wonderful Data Flow Diagram! I love the digital versions and all of the commenting after the diagram to explain the different working parts. This is a good way to portray how your project will work in a finished state. For the Website Idea, a more interactive or modal design for your lo-fi prototype is necessary. Having a good User Task Flow Diagram or User End UI sketch would be a great way to show what happens "up front" when you can't see all of the background working. | Apart from that, I do think this submission is currently unsatisfactory, though it is really close to being good. You should only show the final product of your Lo-Fi prototype visualizations, and not the previous versions in your final submission. Also, please provide more in depth detail in your reflections that what is presented. For example, when you say, "made me realize some different things that I will need to think about," what things? how did this process bring up those questions?

You may now merge D3
