### ISSUE TITLE
Deliverable 4-updates

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#9]
__One sentence overview of your submission__
 Updates on older documentation part of D4

__I would like feedback on ...__ 
Any advice is welcome or criticism

**Comment by schweinsbergs** [comment]
Seeing this project work in class, I was really impressed! I think you have a really good basis for your app and that you're on your way to creating something really good. 

I think that the training data is really going to make or break this project, and I think it was mentioned in class, but just be mindful that different websites and different facets of each website have different connotations to what might be negative words. This is going to be a really weird example, but in the gay community on sites like tumblr and twitter, the f-slur is being reclaimed and is sometimes used in a friendly or joking manner. However, in another community, like 4chan, they may be meaning it. It may be difficult to be able to actually parse through things like that, but I think it's worth thinking about.

**Comment by Alex-Craig** [comment]
I think you have a huge grasp on your project and what you hope to accomplish! Based on what you showed us in class it looks amazing! You have great knowledge of webscrapers and I think that's pretty cool because I can go to you with any questions. I do agree with Sam because a lot of people use words differently in different connotations and it's gonna be a different challenge to look at and try and figure out the different uses of each word. I know some friends who just straight up greet people like, "What's up motherf*ckers?!?" but obviously they mean no harm.

**Comment by alfarozavalae** [comment]
The work you have presented for D4 is really impressive! It is even more impressive to find out in your reflection that a lot of these tools and libraries are new to you. I believe you are doing a great job at doing your own research and figuring out how things on your own but as always if you need help, please let us know. 
As previously mentioned, training data is something to be mindful specially when measuring the sentiment so I believe you might want to consider what your classmates have mentioned about certain websites. (Sorry I do not have specific knowledge about those websites to add here.)
Since now you are working more independently, I believe it would be helpful to start adding issues and dividing the project into small chunks to make sure you are making progress every week. I believe you mentioned the updates needed to the previous deliverables but I do not think you actually went back and made the changes. I think your D3 has not been modified since March 4 so please go back and make the changes you detailed in D4. 
Additionally, it would be a good idea to add comments in the code for things that are new so that if you ever have a bug or need to refactor something you do not have a hard time understanding what you did. /
Great work so far!

**Comment by alfarozavalae** [comment]
Hello Kaleb,
Make sure to close this issue if you no longer have questions or comments to add.

**Comment by alfarozavalae** [comment]
Hello Kaleb,
Make sure to close this issue if you no longer have questions or comments to add.
